FROM node:22-bookworm-slim

USER 1000
RUN mkdir /home/node/app
WORKDIR /home/node/app

COPY --chown=node:node .npmrc ./
COPY --chown=node:node package*.json ./

RUN npm ci --loglevel warn --build-from-source --ignore-scripts

COPY --chown=node:node . .

RUN npm run optimize

EXPOSE 3001
CMD [ "npm", "run", "dev" ]
