name: Main

on:
  push:

jobs:
  build:
    runs-on: ubuntu-22.04
    timeout-minutes: 20

    steps:

      - name: Checkout Code
        uses: actions/checkout@v3

      - name: Build Docker Images
        run: make

      - name: Build Frontend
        run: docker-compose run -T --rm --no-deps frontend npm run build

      - name: Build Backend
        run: docker-compose run -T --rm --no-deps backend npm run build
